SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * C.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN (
    SELECT 
        BOOK_ID,
        SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '01'
    GROUP BY BOOK_ID
) AS C
ON B.BOOK_ID = C.BOOK_ID
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY 1, 3 DESC;