SELECT
    ED.ID AS ID,
    CASE
        WHEN ES.COUNT IS NULL THEN 0
        ELSE ES.COUNT
    END AS CHILD_COUNT
FROM ECOLI_DATA ED
LEFT JOIN (
    SELECT 
    ED.PARENT_ID,
    COUNT(ED.PARENT_ID) AS COUNT
    FROM ECOLI_DATA ED
    GROUP BY ED.PARENT_ID
) AS ES
ON ED.ID = ES.PARENT_ID;