SELECT
    AI.ANIMAL_ID,
    AI.NAME
FROM ANIMAL_INS AI
JOIN ANIMAL_OUTS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE DATEDIFF(AO.DATETIME, AI.DATETIME) > (
    SELECT
        DATEDIFF(AO.DATETIME, AI.DATETIME)
    FROM ANIMAL_INS AI
    JOIN ANIMAL_OUTS AO
    ON AI.ANIMAL_ID = AO.ANIMAL_ID
    ORDER BY DATEDIFF(AO.DATETIME, AI.DATETIME) DESC
    LIMIT 1 OFFSET 2
    )
ORDER BY DATEDIFF(AO.DATETIME, AI.DATETIME) DESC;