SELECT
    RI.REST_ID,
    RI.REST_NAME,
    RI.FOOD_TYPE,
    RI.FAVORITES,
    RI.ADDRESS,
    ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW RR
JOIN (
    SELECT
        *
    FROM REST_INFO
    WHERE ADDRESS LIKE '서울%'
) AS RI
ON RR.REST_ID = RI.REST_ID
GROUP BY RR.REST_ID
ORDER BY 6 DESC, 4 DESC;

