SELECT OS.YEAR AS YEAR, OS.MONTH AS MONTH, UI.GENDER AS GENDER, COUNT(DISTINCT OS.USER_ID) AS USERS
FROM USER_INFO UI
JOIN (
    SELECT 
    ONLINE_SALE_ID, 
    USER_ID, 
    PRODUCT_ID, 
    SALES_AMOUNT, 
    SUBSTRING(SALES_DATE, 1, 4) AS YEAR, 
    CAST(SUBSTRING(SALES_DATE, 6, 2) AS UNSIGNED) AS MONTH
    FROM ONLINE_SALE
) OS
ON UI.USER_ID = OS.USER_ID
WHERE UI.GENDER IS NOT NULL
GROUP BY OS.YEAR, OS.MONTH, UI.GENDER 
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;