SELECT
    YEAR(OS.SALES_DATE) AS YEAR, 
    MONTH(OS.SALES_DATE) AS MONTH, 
    UI.GENDER AS GENDER,
    COUNT(DISTINCT(UI.USER_ID)) AS USERS
FROM (
    SELECT *
    FROM USER_INFO
    WHERE GENDER IS NOT NULL
) AS UI
JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE), UI.GENDER
ORDER BY 1,2,3 ASC;