SELECT 
    DIFFERENTIATION_DATE AS QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM (
    SELECT 
    ID,
    PARENT_ID,
    SIZE_OF_COLONY,
    CASE
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN '01' AND '03' THEN '1Q'
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN '04' AND '06' THEN '2Q'
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN '07' AND '09' THEN '3Q'
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN '10' AND '12' THEN '4Q'
    END AS DIFFERENTIATION_DATE,
    GENOTYPE
FROM ECOLI_DATA
) AS ED
GROUP BY DIFFERENTIATION_DATE
ORDER BY QUARTER 




