SELECT 
    P.ID AS ID,
    P.NAME AS NAME,
    P.HOST_ID AS HOST_ID
FROM PLACES P
JOIN (
    SELECT
        P.HOST_ID AS HOST_ID
    FROM PLACES P
    GROUP BY P.HOST_ID
    HAVING COUNT(P.HOST_ID) >= 2
) AS S
ON P.HOST_ID = S.HOST_ID
ORDER BY P.ID