SELECT
    FP.PRODUCT_ID,
    FP.PRODUCT_NAME,
    FO.TOTAL_AMOUNT * FP.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN (
    SELECT
        PRODUCT_ID,
        SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE YEAR(PRODUCE_DATE) = '2022' AND MONTH(PRODUCE_DATE) = '05'
    GROUP BY PRODUCT_ID
) AS FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
ORDER BY 3 DESC, 1 ASC;
