SELECT 
    E.EMP_NO,
    E.EMP_NAME,
    CASE
        WHEN G.AVG_SCORE >= 96 THEN 'S'
        WHEN G.AVG_SCORE >= 90 THEN 'A'
        WHEN G.AVG_SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN G.AVG_SCORE >= 96 THEN E.SAL * 0.2
        WHEN G.AVG_SCORE >= 90 THEN E.SAL * 0.15
        WHEN G.AVG_SCORE >= 80 THEN E.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES E
JOIN (
    SELECT 
        HG.EMP_NO AS EMP_NO,
        SUM(HG.SCORE) / 2 AS AVG_SCORE
    FROM HR_GRADE HG
    GROUP BY HG.EMP_NO
) AS G
ON E.EMP_NO = G.EMP_NO
ORDER BY E.EMP_NO;

