SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, (B.MAX - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM ECOLI_DATA E 
JOIN (
    SELECT 
      YEAR(DIFFERENTIATION_DATE) AS YEAR, 
      MAX(SIZE_OF_COLONY) AS MAX
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) B
ON YEAR(E.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;