SELECT
    SUM(G.FISH_COUNT) AS FISH_COUNT
FROM (
    SELECT
        COUNT(FI.FISH_TYPE) AS FISH_COUNT
    FROM FISH_INFO FI
    JOIN (
        SELECT
            *
        FROM FISH_NAME_INFO
        WHERE FISH_NAME IN ('BASS', 'SNAPPER')
    ) AS FNI 
    ON FI.FISH_TYPE = FNI.FISH_TYPE
    GROUP BY FI.FISH_TYPE
) AS G