SELECT
    HG.SCORE,
    HG.EMP_NO,
    HE.EMP_NAME,
    HE.POSITION,
    HE.EMAIL
FROM HR_EMPLOYEES HE
JOIN (
    SELECT
        EMP_NO,
        SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) AS HG
ON HE.EMP_NO = HG.EMP_NO
ORDER BY HG.SCORE DESC
LIMIT 1;
