SELECT
    FP.CATEGORY,
    T.MAX_PRICE,
    FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
JOIN (
    SELECT
        CATEGORY,
        MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) AS T
ON FP.CATEGORY = T.CATEGORY AND FP.PRICE = T.MAX_PRICE
WHERE FP.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY T.MAX_PRICE DESC;