SELECT 
    P.CATEGORY,
    P.PRICE AS MAX_PRICE,
    P.PRODUCT_NAME
FROM FOOD_PRODUCT P
WHERE (P.CATEGORY, P.PRICE) IN (
    SELECT CATEGORY, MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)
ORDER BY MAX_PRICE DESC;