SELECT
    COUNT(FI.FISH_TYPE) AS FISH_COUNT,
    MAX(FI.LENGTH) AS MAX_LENGTH,
    FI.FISH_TYPE AS FISH_TYPE
FROM FISH_INFO FI
JOIN (
    SELECT
        CASE
            WHEN AVG(FR.LENGTH) >= 33 THEN FR.FISH_TYPE
        END AS FISH_TYPE
    FROM (
        SELECT
            ID,
            FISH_TYPE,
            IFNULL(LENGTH, 10) AS LENGTH,
            TIME
        FROM FISH_INFO
    ) AS FR
    GROUP BY FR.FISH_TYPE
    ORDER BY AVG(FR.LENGTH) DESC
) AS FE
ON FI.FISH_TYPE = FE.FISH_TYPE
GROUP BY FI.FISH_TYPE
ORDER BY 3 ASC;
